
name: "Build"

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Create directory for ANT keys
      run: mkdir -p ${{ github.workspace }}/firmware/nRF5_SDK_16.0.0/components/ant/ant_key_manager/config/
    - name: Create ANT keys
      uses: RollyPeres/base64-to-path@v1
      with:
        filePath: ${{ github.workspace }}/firmware/nRF5_SDK_16.0.0/components/ant/ant_key_manager/config/ant_key_manager_config.h
        encodedString: ${{ secrets.ANT_KEY_MANAGER_CONFIG }}

    - name: make
      run: docker run -v $(pwd):/workspace ghcr.io/charliebruce/nrf5-docker-build:sdk-16.0.0 bash -c "cd /workspace/firmware && make"
