name: Lint

on: [push, pull_request]

jobs:
  lint:
      runs-on: ubuntu-latest
              
      steps:
        - name: Install cppcheck
          run: sudo apt-get -y install cppcheck
        - uses: actions/checkout@v2

        - name: Create directory for ANT keys
          run: mkdir -p ${{ github.workspace }}/firmware/nRF5_SDK_16.0.0/components/ant/ant_key_manager/config/
        - name: Create ANT keys
          uses: RollyPeres/base64-to-path@v1
          with:
            filePath: ${{ github.workspace }}/firmware/nRF5_SDK_16.0.0/components/ant/ant_key_manager/config/ant_key_manager_config.h
            encodedString: ${{ secrets.ANT_KEY_MANAGER_CONFIG }}

        - name: "Run cppcheck"
          run: cppcheck --enable=all --error-exitcode=1 -ifirmware/nRF5_SDK_16.0.0 firmware/
